// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvsApp.Data;

#nullable disable

namespace MyMvsApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250211123107_AddedSeededDataDiaryEntry")]
    partial class AddedSeededDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyMvsApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the first entry in the diary.",
                            Created = new DateTime(2025, 2, 11, 12, 31, 6, 9, DateTimeKind.Local).AddTicks(2739),
                            Title = "First Entry"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is the second entry in the diary.",
                            Created = new DateTime(2025, 2, 11, 12, 31, 6, 9, DateTimeKind.Local).AddTicks(3069),
                            Title = "Second Entry"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is the third entry in the diary.",
                            Created = new DateTime(2025, 2, 11, 12, 31, 6, 9, DateTimeKind.Local).AddTicks(3073),
                            Title = "Third Entry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
